name: Scrape y actualizar agenda

on:
  schedule:
    - cron: '30 10 * * *'  # 5:30 AM
    - cron: '0 13 * * *'   # 8:00 AM
    - cron: '0 17 * * *'   # 12:00 PM
    - cron: '0 20 * * *'   # 3:00 PM
    - cron: '0 23 * * *'   # 6:00 PM
    - cron: '0 2 * * *'    # 9:00 PM
  workflow_dispatch:       # Permite ejecutar manualmente también

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Python y dependencias
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar requerimientos
      run: |
        pip install beautifulsoup4 playwright
        playwright install chromium

    - name: Ejecutar script de scraping
      run: |
        python scrap_agenda_librefutbol.py

    - name: Subir agenda_resultado.json al repositorio
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Actualizar agenda automáticamente"
        file_pattern: agenda_resultado.json
